# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib_seq_even(n):
    '''Returns the sum of even numbers in a Fibonacci sequence whose values do not exceed n'''
    sum = 0
    a, b = 0, 1 #initializing loop variables
                 
    while a < n:       
        a, b = b, a + b 
        if b%2 == 0:   #Checking if fibonacci number is even
            sum += b
        
                
    return sum



