# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


sum = 0
fib1 = 1  #initialize loop variables
fib2 = 1

while fib1 < 4000000 or fib2 < 4000000:
    fib1 = fib1 + fib2
    fib2 = fib1 + fib2

    if fib1%2 == 0:   #Checking if fibonacci series' number is even
        sum += fib1

    if fib2%2 == 0:
        sum += fib2

print (sum)


